In [3]:
import torch
import numpy as np

# Check version
print(torch.__version__)

2.2.2


In [10]:
m = torch.tensor([[1.0, 2.0, 3.0, 7.0],
                   [4.0, 5.0, 6.0, 8.0],
                   [7.0, 8.0, 9.0, 9.0],
                   [10.0, 11.0, 12.0, 10.0]])
print(m.shape)
print(m.dtype)
print(m.mean())

torch.Size([4, 4])
torch.float32
tensor(7.)


In [11]:
# Create two 3x3 matrices A and B
A = torch.tensor([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0],
                  [7.0, 8.0, 9.0]])
B = torch.tensor([[9.0, 8.0, 7.0],
                  [6.0, 5.0, 4.0],
                  [3.0, 2.0, 1.0]]) 

# Print element-wise multiplication
print(A * B)

# Print matrix multiplication
print(A @ B)

# Print the difference in results
print((A * B) - (A @ B))

tensor([[ 9., 16., 21.],
        [24., 25., 24.],
        [21., 16.,  9.]])
tensor([[ 30.,  24.,  18.],
        [ 84.,  69.,  54.],
        [138., 114.,  90.]])
tensor([[ -21.,   -8.,    3.],
        [ -60.,  -44.,  -30.],
        [-117.,  -98.,  -81.]])


In [12]:
# Create a tensor x = 5.0 with requires_grad=True
x = torch.tensor(5.0, requires_grad=True)

# Compute y = 3x² + 2x + 1
y = 3 * x**2 + 2 * x + 1
# Call backward()
y.backward()

# Print x.grad — what do you expect it to be mathematically?
print(x.grad)

tensor(32.)


In [13]:
# Create a NumPy array
np_array = np.array([1.0, 2.0, 3.0, 4.0, 5.0])

# Convert to PyTorch tensor
tensor = torch.from_numpy(np_array)
print(tensor)
print(tensor.dtype)

# Convert back to NumPy
back_to_numpy = tensor.numpy()
print(back_to_numpy)
print(type(back_to_numpy))

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)
torch.float64
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>


In [14]:
# Check if GPU is available
print(torch.cuda.is_available())
# On Mac with Apple Silicon:
print(torch.backends.mps.is_available())

False
False
